### ISSUE TITLE
design interface design plan

### ISSUE THREAD

**Issue by danqo** [MyMood-Alexa/MyMood#11]

**Comment by dionwu110** [comment]
Current plan:
We want to use this video as reference for our main login page:
https://www.youtube.com/watch?v=93QK-byrx9k&t=129s

![image](https://user-images.githubusercontent.com/14339815/45274334-e6b63000-b46b-11e8-9a86-e189fbad31a9.png)

And this video as reference for the database table:
https://www.youtube.com/watch?v=dONi5PSU50A

![image](https://user-images.githubusercontent.com/14339815/45274374-1c5b1900-b46c-11e8-810d-198348b5294e.png)

**Comment by jtam360** [comment]
**Technology Stack:**
HTML (Markup Language)
CSS (Style Sheet Language)
JavaScript (Scripting Language)
Bootstrap (Presentation Frameworks)

**Comment by lydarren** [comment]
I think the login is fine/good but it doesn't have to look that fancy for our application. 
How would the conversation between the device and the user look in that table? Assuming they go back and forth 10 times, that's a total of 20 lines for one session. If you were to just add all the responses into one cell per session, it would leave a lot of empty spaces in the other cells due to stretching out vertically.

**Comment by jtam360** [comment]
We can have the most recent conversation be displayed with an option either at the beginning or end of that to expand so you can see the rest of the lines. I think this option will also lead to a lot of empty spaces in other cells since it'll stretch, but only after the user decides to expand that particular cell.

**Comment by danqo** [comment]
That implementation sort of implementation is sort of fancy. I'm not sure how hard it would be, but I'd recommend doing a simpler, straight forward implementation first so that you have something by the end of the sprint. If that works, then you can go ahead and do the expanding implementation. Make sure you test the expanding implementation with fake data to ensure its compatible with the data being held in the backend; otherwise you'll run into issues when you do start doing the backend work.

**Comment by danqo** [comment]
Can dion or jeffrey edit their original posts noting this implementation detail?

HTML, CSS, and Bootstrap are all frontend tools. Is JavaScript what you plan on using for your backend?
